# Generated by Django 6.0.5 on 2026-06-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_manifestorating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='manifesto',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='manifesto',
            name='category',
        ),
        migrations.AddField(
            model_name='candidate',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='manifesto',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='manifestos', to='core.category'),
        ),
    ]
